version: 0.0
os: linux
files:
  - source: target/java-cicd-pipeline.war # REMOVED the leading slash
    destination: /var/lib/tomcat10/webapps/ # UPDATED to Amazon Linux 2023 native path
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

