version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to AWS CodeArtifact...
      - AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ":")
      - echo "Extracted Account ID is $AWS_ACCOUNT_ID"
      - CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ssd --domain-owner $AWS_ACCOUNT_ID --region eu-south-1 --query authorizationToken --output text`
      - export CODEARTIFACT_AUTH_TOKEN
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -s settings.xml # Swapped to simple clean package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging artifacts...
      - mvn package -s settings.xml
artifacts:
  files:
    - target/java-cicd-pipeline.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no

